/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { RigidBody } from '@react-three/rapier';

export default function Basketball(props) {
  const { nodes, materials } = useGLTF('./BasketballFixed.glb');
  return (
    <RigidBody
      position={[1, 20, 0]}
      colliders="ball"
      scale={10}
      restitution={1}
    >
      <mesh
        geometry={nodes.basketball.geometry}
        material={materials.Basketball}
      />
    </RigidBody>
  );
}

useGLTF.preload('./BasketballFixed.glb');
